version: '3.8'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret$tr0ngP@ssw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  api:
    build: .
    container_name: basicblogapi
    depends_on:
      - db
    environment:
      - ConnectionStrings__BasicBlogPlatformConnection=Server=db,1433;Database=BasicBlogPlatformDb;User Id=sa;Password=Secret$tr0ngP@ssw0rd;TrustServerCertificate=True;
    ports:
      - "8080:80"

volumes:
  mssql_data:
